server.port=8080

spring.profiles.active=dev
#actuator properties
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true


spring.jpa.hibernate.ddl-auto = update
